// Generated by gencpp from file security_decentralize_pkg/custom_3.msg
// DO NOT EDIT!


#ifndef SECURITY_DECENTRALIZE_PKG_MESSAGE_CUSTOM_3_H
#define SECURITY_DECENTRALIZE_PKG_MESSAGE_CUSTOM_3_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>
#include <geometry_msgs/Pose2D.h>

namespace security_decentralize_pkg
{
template <class ContainerAllocator>
struct custom_3_
{
  typedef custom_3_<ContainerAllocator> Type;

  custom_3_()
    : robot_name()
    , location()  {
    }
  custom_3_(const ContainerAllocator& _alloc)
    : robot_name(_alloc)
    , location(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _robot_name_type;
  _robot_name_type robot_name;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _location_type;
  _location_type location;





  typedef boost::shared_ptr< ::security_decentralize_pkg::custom_3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::security_decentralize_pkg::custom_3_<ContainerAllocator> const> ConstPtr;

}; // struct custom_3_

typedef ::security_decentralize_pkg::custom_3_<std::allocator<void> > custom_3;

typedef boost::shared_ptr< ::security_decentralize_pkg::custom_3 > custom_3Ptr;
typedef boost::shared_ptr< ::security_decentralize_pkg::custom_3 const> custom_3ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::security_decentralize_pkg::custom_3_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::security_decentralize_pkg::custom_3_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::security_decentralize_pkg::custom_3_<ContainerAllocator1> & lhs, const ::security_decentralize_pkg::custom_3_<ContainerAllocator2> & rhs)
{
  return lhs.robot_name == rhs.robot_name &&
    lhs.location == rhs.location;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::security_decentralize_pkg::custom_3_<ContainerAllocator1> & lhs, const ::security_decentralize_pkg::custom_3_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace security_decentralize_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::security_decentralize_pkg::custom_3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::security_decentralize_pkg::custom_3_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::security_decentralize_pkg::custom_3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::security_decentralize_pkg::custom_3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::security_decentralize_pkg::custom_3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::security_decentralize_pkg::custom_3_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::security_decentralize_pkg::custom_3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc4b6bfc08bf9f97dcec3e07cd0e259b";
  }

  static const char* value(const ::security_decentralize_pkg::custom_3_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc4b6bfc08bf9f97ULL;
  static const uint64_t static_value2 = 0xdcec3e07cd0e259bULL;
};

template<class ContainerAllocator>
struct DataType< ::security_decentralize_pkg::custom_3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "security_decentralize_pkg/custom_3";
  }

  static const char* value(const ::security_decentralize_pkg::custom_3_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::security_decentralize_pkg::custom_3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String robot_name\n"
"geometry_msgs/Pose2D location\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::security_decentralize_pkg::custom_3_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::security_decentralize_pkg::custom_3_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_name);
      stream.next(m.location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct custom_3_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::security_decentralize_pkg::custom_3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::security_decentralize_pkg::custom_3_<ContainerAllocator>& v)
  {
    s << indent << "robot_name: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.robot_name);
    s << indent << "location: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.location);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SECURITY_DECENTRALIZE_PKG_MESSAGE_CUSTOM_3_H
