// Generated by gencpp from file security_decentralize_pkg/malicious_flags.msg
// DO NOT EDIT!


#ifndef SECURITY_DECENTRALIZE_PKG_MESSAGE_MALICIOUS_FLAGS_H
#define SECURITY_DECENTRALIZE_PKG_MESSAGE_MALICIOUS_FLAGS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>
#include <std_msgs/String.h>
#include <std_msgs/String.h>

namespace security_decentralize_pkg
{
template <class ContainerAllocator>
struct malicious_flags_
{
  typedef malicious_flags_<ContainerAllocator> Type;

  malicious_flags_()
    : bot1_mal()
    , bot2_mal()
    , bot3_mal()  {
    }
  malicious_flags_(const ContainerAllocator& _alloc)
    : bot1_mal(_alloc)
    , bot2_mal(_alloc)
    , bot3_mal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _bot1_mal_type;
  _bot1_mal_type bot1_mal;

   typedef  ::std_msgs::String_<ContainerAllocator>  _bot2_mal_type;
  _bot2_mal_type bot2_mal;

   typedef  ::std_msgs::String_<ContainerAllocator>  _bot3_mal_type;
  _bot3_mal_type bot3_mal;





  typedef boost::shared_ptr< ::security_decentralize_pkg::malicious_flags_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::security_decentralize_pkg::malicious_flags_<ContainerAllocator> const> ConstPtr;

}; // struct malicious_flags_

typedef ::security_decentralize_pkg::malicious_flags_<std::allocator<void> > malicious_flags;

typedef boost::shared_ptr< ::security_decentralize_pkg::malicious_flags > malicious_flagsPtr;
typedef boost::shared_ptr< ::security_decentralize_pkg::malicious_flags const> malicious_flagsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::security_decentralize_pkg::malicious_flags_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::security_decentralize_pkg::malicious_flags_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::security_decentralize_pkg::malicious_flags_<ContainerAllocator1> & lhs, const ::security_decentralize_pkg::malicious_flags_<ContainerAllocator2> & rhs)
{
  return lhs.bot1_mal == rhs.bot1_mal &&
    lhs.bot2_mal == rhs.bot2_mal &&
    lhs.bot3_mal == rhs.bot3_mal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::security_decentralize_pkg::malicious_flags_<ContainerAllocator1> & lhs, const ::security_decentralize_pkg::malicious_flags_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace security_decentralize_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::security_decentralize_pkg::malicious_flags_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::security_decentralize_pkg::malicious_flags_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::security_decentralize_pkg::malicious_flags_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::security_decentralize_pkg::malicious_flags_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::security_decentralize_pkg::malicious_flags_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::security_decentralize_pkg::malicious_flags_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::security_decentralize_pkg::malicious_flags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1fbd4377f4fa1942d302cc06fa5d8c8f";
  }

  static const char* value(const ::security_decentralize_pkg::malicious_flags_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1fbd4377f4fa1942ULL;
  static const uint64_t static_value2 = 0xd302cc06fa5d8c8fULL;
};

template<class ContainerAllocator>
struct DataType< ::security_decentralize_pkg::malicious_flags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "security_decentralize_pkg/malicious_flags";
  }

  static const char* value(const ::security_decentralize_pkg::malicious_flags_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::security_decentralize_pkg::malicious_flags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String bot1_mal\n"
"std_msgs/String bot2_mal\n"
"std_msgs/String bot3_mal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::security_decentralize_pkg::malicious_flags_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::security_decentralize_pkg::malicious_flags_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bot1_mal);
      stream.next(m.bot2_mal);
      stream.next(m.bot3_mal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct malicious_flags_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::security_decentralize_pkg::malicious_flags_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::security_decentralize_pkg::malicious_flags_<ContainerAllocator>& v)
  {
    s << indent << "bot1_mal: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.bot1_mal);
    s << indent << "bot2_mal: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.bot2_mal);
    s << indent << "bot3_mal: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.bot3_mal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SECURITY_DECENTRALIZE_PKG_MESSAGE_MALICIOUS_FLAGS_H
