# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from security_decentralize_pkg/malicious_flags.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class malicious_flags(genpy.Message):
  _md5sum = "1fbd4377f4fa1942d302cc06fa5d8c8f"
  _type = "security_decentralize_pkg/malicious_flags"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/String bot1_mal
std_msgs/String bot2_mal
std_msgs/String bot3_mal

================================================================================
MSG: std_msgs/String
string data
"""
  __slots__ = ['bot1_mal','bot2_mal','bot3_mal']
  _slot_types = ['std_msgs/String','std_msgs/String','std_msgs/String']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       bot1_mal,bot2_mal,bot3_mal

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(malicious_flags, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.bot1_mal is None:
        self.bot1_mal = std_msgs.msg.String()
      if self.bot2_mal is None:
        self.bot2_mal = std_msgs.msg.String()
      if self.bot3_mal is None:
        self.bot3_mal = std_msgs.msg.String()
    else:
      self.bot1_mal = std_msgs.msg.String()
      self.bot2_mal = std_msgs.msg.String()
      self.bot3_mal = std_msgs.msg.String()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.bot1_mal.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.bot2_mal.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.bot3_mal.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.bot1_mal is None:
        self.bot1_mal = std_msgs.msg.String()
      if self.bot2_mal is None:
        self.bot2_mal = std_msgs.msg.String()
      if self.bot3_mal is None:
        self.bot3_mal = std_msgs.msg.String()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.bot1_mal.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.bot1_mal.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.bot2_mal.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.bot2_mal.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.bot3_mal.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.bot3_mal.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.bot1_mal.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.bot2_mal.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.bot3_mal.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.bot1_mal is None:
        self.bot1_mal = std_msgs.msg.String()
      if self.bot2_mal is None:
        self.bot2_mal = std_msgs.msg.String()
      if self.bot3_mal is None:
        self.bot3_mal = std_msgs.msg.String()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.bot1_mal.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.bot1_mal.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.bot2_mal.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.bot2_mal.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.bot3_mal.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.bot3_mal.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
